apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "ExploreMe"
  description: "Discover backstage"
  annotations:
    github.com/project-slug: jinniiiee/backbencher
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
  definition: |
    openapi: "3.0.1"
    info:
      version: v0.1
      title: Explore Financing
      license:
        name: S x B
    servers:
      - url: https://document-service.dev.sebx.se/swagger-ui/index.html
    paths:
      /api/play/greet:
        get:
          summary: Get a nice greeting
